### ISSUE TITLE
5+ second delay when loading and playing new song

### ISSUE THREAD

**Issue by jasongrishkoff** [Guichaguri/react-native-track-player#14]
```
05-03 08:20:26.466 14864 15001 I ReactNativeJS: { player: 0, type: 'player-playing' }
05-03 08:20:26.470 14864 15001 I ReactNativeJS: { player: 0, type: 'player-state', state: 6 }
05-03 08:20:32.418 14864 15001 I ReactNativeJS: { player: 0, type: 'player-pause' }
05-03 08:20:32.425 14864 15001 I ReactNativeJS: { player: 0, type: 'player-state', state: 2 }
05-03 08:20:32.432 14864 15001 I ReactNativeJS: { player: 0, type: 'player-loaded', track: '1234' }
05-03 08:20:32.463 14864 15001 I ReactNativeJS: { player: 0, type: 'player-playing' }
05-03 08:20:32.490 14864 15001 I ReactNativeJS: { player: 0, type: 'player-state', state: 3 }
```

As you can see from the timestamp, it takes roughly 6 seconds to actually start playing a song.  Is it trying to download the full song before playing?

**Comment by jasongrishkoff** [comment]
I'm guessing this has something to do with MediaPlayer not being able to do 206?  And ExoPlayer can handle it using dash?  So on load() I'd need to set type:"dash"?

**Comment by Guichaguri** [comment]
This is not a bug, but rather a MediaPlayer behavior. It takes time to open a request to the URL and load the very first bytes.
I don't know if ExoPlayer handles this better, you can try adding `compile 'com.google.android.exoplayer:exoplayer:r2.3.1'` to the `dependencies` block in your build.gradle to use ExoPlayer instead of MediaPlayer.
For DASH, the server would need to support DASH streams, and AFAIK SoundCloud doesn't.

**Comment by jasongrishkoff** [comment]
*Significantly* faster.  From 5 seconds to less than 1 second.  I think ExoPlayer can handle partial content (206 response), and it seems MediaPlayer can't.

What do I lose by using ExoPlayer?

**Comment by Guichaguri** [comment]
The size of your app will increase by a megabyte or two. It's not much, ProGuard can always help reduce it

**Comment by Guichaguri** [comment]
I'm also looking forward to Android O's MediaPlayer improvements, it might fix issues like this

**Comment by jasongrishkoff** [comment]
Cool, for now I'll use ExoPlayer. Should I set up another json file to avoid updates to this library overriding my compile change? I see it references a json file to see if it should use ExoPlayer...

**Comment by Guichaguri** [comment]
You can create a `track-player.json` file in the main directory of your RN project, in the json, you can set `dash`, `hls` or `smoothstreaming` to true and ExoPlayer will be automatically added. I'll change it to just `exoplayer` in the future.

```json
{
    "exoplayer": true,
    "cache": false
}
```

**Comment by jasongrishkoff** [comment]
Great, thanks.  Have added that track-player.json file and from what I can tell, it's not really taking effect.

ExoPlayer definitely provides a better listening experience as far as streaming music from track to track.  The playback is almost instant when loading a new track.

**Comment by Guichaguri** [comment]
@jasongrishkoff You are setting `dash`, `hls` or `smoothstreaming` to true, right? It's not changed yet to just `exoplayer`.

ExoPlayer is far better than the Android player for sure, and both of them can load faster if I pre-load the next track while the current one plays, which I plan to do.

**Comment by jasongrishkoff** [comment]
The preloading will help with internet connection loss -- it happened to me a few times today while I was out and about that I lost internet connection, and the player never really recovered.  It's a tough situation to manage...

My track-player.json simple was just a copy-paste of what you'd have above -- I understand where I went wrong.  You're saying this is what you want it to be, but for now I should add something like `"dash":true` for it to work.

```
{
    "exoplayer": true,
    "cache": false
}
```
