### ISSUE TITLE
Possible to insertAfterId instead of insertBeforeId on add()?

### ISSUE THREAD

**Issue by jasongrishkoff** [Guichaguri/react-native-track-player#15]
The functionality I'm trying to accomplish is:

1. User hits play on a song, and I load() that song
2. In the background, I fetch the accompanying playlist of next songs for that song
3. I then create an object of the new songs, and try to add() them

I'd want this new playlist to fill in *after* the current song.  Is that possible?

**Comment by jasongrishkoff** [comment]
Seems like keeping insertBeforeId as "null" accomplishes this. Am I right?

**Comment by Guichaguri** [comment]
Yes, you are. I forgot to add it to the documentation

**Comment by jasongrishkoff** [comment]
Thanks for confirming.
