### ISSUE TITLE
skipToNext on player-ended leapfrogs a song

### ISSUE THREAD

**Issue by jasongrishkoff** [Guichaguri/react-native-track-player#16]
Let's say I have tracks 1,2,3,4.  When 1 finishes playing, I want to fire skipToNext on player-ended in background headless task. This seems to start track 3, rather than track 2? However, if song 1 is mid-way through and I get impatient and decide to move along, triggering skipToNext while player-playing takes me to 2, as expected.

**Comment by Guichaguri** [comment]
You don't call skipToNext when a track ends. The player automatically does that for you.

**Comment by jasongrishkoff** [comment]
Right you are! Thank you.
