### ISSUE TITLE
Ability to see skip/previous controls in compact notification view

### ISSUE THREAD

**Issue by jasongrishkoff** [Guichaguri/react-native-track-player#18]
If the user has set options for PREV or SKIP, it'd be nice to use .setShowActionsInCompactView(0, 1, 2)) as part of the notification builder, so that those actions can also be seen in the compact view. Thoughts?

**Comment by Guichaguri** [comment]
What about adding in the options an array of capabilities for the compact view?

**Comment by jasongrishkoff** [comment]
Totally cool with that.

**Comment by Guichaguri** [comment]
Added in b270e6d69117bb608b74dca34827259b29304389
