### ISSUE TITLE
Queue/Playlist API

### ISSUE THREAD

**Issue by Guichaguri** [Guichaguri/react-native-track-player#2]
This is not only a good idea for general design, but it also helps for better performance on Chromecast devices.

APIs that are going to change:
* `setMetadata()` will be removed. `load()` will be accepting metadata
* `load()` can be called multiple times. The songs will be added to the queue
* `reset()` will now reset the queue

APIs that are going to be added:
* `skip()` will skip to a song based on ID
* `skipToNext()` will skip to the next song 
* `skipToPrevious()`will skip to the previous song
* Functions for removing/clearing the queue without resetting the player

It might be a good idea to rename `load()` to something else

**Comment by Guichaguri** [comment]
For this API, I'll need the state to become more reliable, I think I'll have to remove the callback from `load` and implement it as an event.
`play`, `pause` and other functions will work even though the track is not yet loaded, so if you load and then play, the track will play after it was loaded.

@jasongrishkoff Are you okay with this change?

**Comment by jasongrishkoff** [comment]
Sounds great -- I was already firing play() inside the callback; can just run the afterwards.

**Comment by jasongrishkoff** [comment]
Been keeping an eye on your commits.  Let me know when I can help test this out.

**Comment by Guichaguri** [comment]
The playlist implementation is almost done, I'll let you know when it's ready for testing :)

**Comment by Guichaguri** [comment]
I think it's ready, I still haven't tested everything, but it should work.

**Comment by jasongrishkoff** [comment]
Great! Does the Wiki need updating?

**Comment by Guichaguri** [comment]
Yes, I'll update it tomorrow

**Comment by jasongrishkoff** [comment]
Thx! Going to today / this weekend.

**Comment by Guichaguri** [comment]
@jasongrishkoff I didn't have time to update the API page yet, but I have created a [documentation](https://github.com/Guichaguri/react-native-track-player/wiki/Documentation) page with every API function, constant or event. I'll try to work on the API page tomorrow

**Comment by ashokkumar88** [comment]
@jasongrishkoff i can't find in the documentation or source code the load() function. Is this function renamed?

**Comment by jasongrishkoff** [comment]
@ashokkumar88 yeah this thread is nearly 1 year old, and the API has changed a lot since then!
