### ISSUE TITLE
[ios] Swift is not supported for static libraries

### ISSUE THREAD

**Issue by anderslemke** [Guichaguri/react-native-track-player#27]
After linking, I get this error when trying to build in XCode:

![screen shot 2017-08-15 at 15 48 27](https://user-images.githubusercontent.com/708095/29318619-3623b23a-81d1-11e7-9046-1bad62090f29.png)

Can I fix this somehow?

**Comment by jasongrishkoff** [comment]
Hey @anderslemke -- it actually requires Xcode beta for Swift right now.  Are you able to install that?

**Comment by anderslemke** [comment]
Oh! I will try... :)

**Comment by dcvz** [comment]
@anderslemke as @jasongrishkoff said, you'll need the latest Xcode 9 beta for this to work

**Comment by anderslemke** [comment]
Now I've updated, and that first error went away.
I have new one now, though... :)

    ld: library not found for -lswiftCoreAudio for architecture x86_64

I will investigate.

**Comment by anderslemke** [comment]
I tried this: https://stackoverflow.com/a/39630099/923539

But it doesn't work...

**Comment by dcvz** [comment]
Hey @anderslemke are you working with a default xcode project? The ones generated by the react-native cli?

**Comment by anderslemke** [comment]
I would say so. It was, however, not generated with the latest version of React.

**Comment by dcvz** [comment]
Can you try adding a swift file to your project? You can call it `dummy.swift` then you will be prompted if you want to generate a bridging header. Say yes, and then try building again :)

We've yet to formalize the documentation for this.

**Comment by anderslemke** [comment]
Yes! I created the `dummy.swift`. 
XCode failed, and gave me the path to the header file it was missing. So I created that file:

    touch /Users/anders/Projects/zetland/lyd-react-native/ios/LydReactNative-Bridging-Header.h

Now it works! 🎉
