### ISSUE TITLE
iOS automatic next song not actually playing?

### ISSUE THREAD

**Issue by jasongrishkoff** [Guichaguri/react-native-track-player#29]
As reported via chat, the eventEmitter works fine to detect that the track has changed, but the new song doesn't actually start playing?  skipToNext() works fine, just not the automatic switch.  Have you seen this on your side?

**Comment by dcvz** [comment]
I haven't had time to look. I will try to get to it as soon as I can :)

**Comment by jasongrishkoff** [comment]
@dcvz any luck confirming this?

**Comment by dcvz** [comment]
This bug has now been fixed 💃
