### ISSUE TITLE
AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/DefaultRenderersFactory;

### ISSUE THREAD

**Issue by anderslemke** [Guichaguri/react-native-track-player#30]
I get this exception when running `setupPlayer` on Android simulator:

```
08-16 09:03:31.761  1349  1349 D AndroidRuntime: Shutting down VM
08-16 09:03:31.810  1349  1349 E AndroidRuntime: FATAL EXCEPTION: main
08-16 09:03:31.810  1349  1349 E AndroidRuntime: Process: com.zetland, PID: 1349
08-16 09:03:31.810  1349  1349 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/DefaultRenderersFactory;
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at guichaguri.trackplayer.player.players.ExoPlayback.<init>(ExoPlayback.java:62)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at guichaguri.trackplayer.logic.MediaManager.createLocalPlayback(MediaManager.java:74)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at guichaguri.trackplayer.logic.MediaManager.setupPlayer(MediaManager.java:87)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at guichaguri.trackplayer.logic.services.PlayerService.onBind(PlayerService.java:33)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:3218)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at android.app.ActivityThread.-wrap3(ActivityThread.java)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1572)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.DefaultRenderersFactory" on path: DexPathList[[zip file "/data/app/com.zetland-1/base.apk"],nativeLibraryDirectories=[/data/app/com.zetland-1/lib/x86, /system/fake-libs, /data/app/com.zetland-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
08-16 09:03:31.810  1349  1349 E AndroidRuntime: 	... 13 more
08-16 09:03:31.811   603   716 W ActivityManager:   Force finishing activity com.zetland/.MainActivity
```

Any help is appreciated. :)

**Comment by jasongrishkoff** [comment]
You're working from the dev branch, right? The documentation hasn't fully updated to reflect that we replaced setupPlayer.  This is what I use to initiate:

```
    componentDidMount() {                                                                                              
        this.startTrackPlayer()
    }
    
    startTrackPlayer = async() => {
        await TrackPlayer.setupPlayer({})
        TrackPlayer.updateOptions({                                                                                    
            maxArtworkSize: 1000,                                                                                      
            capabilities: [
                TrackPlayer.CAPABILITY_PLAY,                                                                           
                TrackPlayer.CAPABILITY_PAUSE,
                TrackPlayer.CAPABILITY_SKIP_TO_NEXT,                                                                   
                TrackPlayer.CAPABILITY_SKIP_TO_PREVIOUS                                                                
            ],
        })
        // We need to track things on iOS                                                                              
        if (Platform.OS == 'ios') {                                                                                    
            TrackPlayer.eventEmitter.addListener('playback-track-changed', () => {                                     
                updatePlayerSong()
            })
        }
    } 
```

**Comment by anderslemke** [comment]
Yes. I'm on the dev branch.

I will try your setup code. :)

**Comment by anderslemke** [comment]
That didn't seem to fix it...

**Comment by jasongrishkoff** [comment]
Have you got Play Services installed?

**Comment by anderslemke** [comment]
Good question. :)
I do not know what that is...

**Comment by jasongrishkoff** [comment]
Have you got Android Studio?
https://developers.google.com/android/guides/setup

1. Start Android Studio.
2. On the Tools menu, click Android > SDK Manager.
3. Update the Android Studio SDK Manager: click SDK Tools, expand Support Repository, select Google Repository, and then click OK.

**Comment by anderslemke** [comment]
I'm running the app in a simulator... Not on a device. That wasn't clear from the first message. Sorry.

**Comment by anderslemke** [comment]
I've now updated "Google Repository" from 55 to 57.
But I still get the error.

I'm using Genymotion. Let me try using the Android Studio simulator.

**Comment by jasongrishkoff** [comment]
Have you added it to your dependencies in android/app/build.gradle?

**Comment by anderslemke** [comment]
Oh. I should do that? I figured it was included somewhere else...
I already have the `compile project(':react-native-track-player')` in there.

**Comment by jasongrishkoff** [comment]
You might need to add this one at the very least:

 `compile 'com.google.android.gms:play-services-cast:9.4.0'`

Have you got this?
`compile 'com.android.support:appcompat-v7:23.0.1'`

**Comment by anderslemke** [comment]
OK. I'm adding

    compile 'com.google.android.gms:play-services:11.2.0'

I already had

    compile "com.android.support:appcompat-v7:23.4.0"

**Comment by anderslemke** [comment]
Now I've added 

    compile 'com.google.android.gms:play-services-cast:9.4.0'

And already got 

    compile "com.android.support:appcompat-v7:23.4.0"

But still no luck. Same error.

**Comment by anderslemke** [comment]
OK. I think I found it.

It seems to break if I do not include `track-player.json` with `"exoplayer": true,`.

Now I got it working. Thanks for your patience @jasongrishkoff

**Comment by Guichaguri** [comment]
@anderslemke That is still an issue, it should still work without using ExoPlayer, I'll reopen it for now

**Comment by Guichaguri** [comment]
It seems like an older version of ExoPlayer was being used instead.
It's either another music module using an older ExoPlayer version or you didn't cleaned up the dependencies after installing this module.

**Comment by wkmcyz** [comment]
> It seems like an older version of ExoPlayer was being used instead.
> It's either another music module using an older ExoPlayer version or you didn't cleaned up the dependencies after installing this module.

Yes, it is truly because another module using a different version of ExoPlayer. I had this problem and I fixed it by removing `react-native-video` module.

**Comment by jeremyfrancis** [comment]
> > It seems like an older version of ExoPlayer was being used instead.
> > It's either another music module using an older ExoPlayer version or you didn't cleaned up the dependencies after installing this module.
> 
> Yes, it is truly because another module using a different version of ExoPlayer. I had this problem and I fixed it by removing `react-native-video` module.

I have found this is the issue whereas I am using expo-av for Videos and react-native-track-player but they do not agree on the same version of ExoPlayer.

Your solution is accurate, but if we need both modules it is not a valid solution.

Any ideas?

**Comment by divitrao** [comment]
Any solution on this , im using react native video as well and i cant uninstall it as it is required ?
