### ISSUE TITLE
I noticed voice calls will resume a paused player

### ISSUE THREAD

**Issue by jasongrishkoff** [Guichaguri/react-native-track-player#4]
If I had a notifcation open but paused it -- coming back 20 minutes later to make a WhatsApp phone call triggers the audio again and it starts playing while I'm making my call. As soon as I hang up, it stops playing. I also noticed the issue while recording a voice note -- when I started recording, the music came back on; as soon as I stopped, the music ended.

**Comment by Bisark** [comment]
I observe the same issue when sending a Whatsapp voice message
