### ISSUE TITLE
Play from specific position

### ISSUE THREAD

**Issue by anderslemke** [Guichaguri/react-native-track-player#42]
Our app often needs to play from a specific position in the track. I.e. not just from the start.

It would be nice to have an option for this. Maybe something like:

```js
TrackPlayer.add(infos).then( () => {
  TrackPlayer.skip(trackId, 100);
});
```

where 100 is the position I would like to start at.

**Comment by dcvz** [comment]
so you should be able to do:
```js
await TrackPlayer.add(...)
await TrackPlayer.skip(...)
await TrackPlayer.seekTo(time)
```

is that not working as it should?

**Comment by anderslemke** [comment]
Holy moly. Off course that works! Sorry.
It didn't work in the old player I was using. Algorithm spillover... Sorry again.

**Comment by ithustle** [comment]
> is that not working as it should?

Works on Android but crash the app on iOS
