### ISSUE TITLE
Split Chromecast code into another module

### ISSUE THREAD

**Issue by Guichaguri** [Guichaguri/react-native-track-player#5]
Since Chromecast require Google Play Services and its library available, it would be better to split the Chromecast code into another module.

I'm still thinking into creating a submodule (where you need react-native-track-player to run it) or an independent module (Chromecast focused, but it has special support to react-native-track-player)

**Comment by jasongrishkoff** [comment]
Just curious -- does it take up extra memory/resources/battery to have that library available?

**Comment by Guichaguri** [comment]
A few special libraries require apps installed and don't actually need the code included in your app.
The Cast library only includes an abstraction to the actual API. This makes the library to use less space, but it still does a little bit.

![](https://developers.google.com/android/images/play-services-diagram.png)

**Comment by Guichaguri** [comment]
I don't know if I'm too paranoid about it... Maybe I am
Only music/video apps would use this module, and all of them should support Chromecast anyway.

In case you are wondering, the Cast library adds up just about 223kb

**Comment by jasongrishkoff** [comment]
Given that a lot of apps are ~10mb, I think that the 223kb is minor.  I feel you -- I'm really focused on keeping things lean and lightweight.  But, Chromecast is an integral part of a music Android app, so I think having it in the same package would be a good idea.

**Comment by Guichaguri** [comment]
You're right. Not to even mention that you can even reduce those 223kb using ProGuard
