### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jasongrishkoff** [Guichaguri/react-native-track-player#7]
React Native v0.43.3

Could be a conflict with another library, but seems one needs to add to app/build.gradle as follows:

    compile(project(':react-native-track-player')) {
        exclude group: "com.google.android.gms" // very important
    }

Doing that allows app to build, but results in attached.  Working through that now.
![screenshot_1492260953](https://cloud.githubusercontent.com/assets/375379/25063683/cbbf5aa6-21eb-11e7-8191-eb23f61081bb.png)

**Comment by jasongrishkoff** [comment]
Removing the package solves the problem, so that seems to isolate it to react-native-track-player

**Comment by Guichaguri** [comment]
You can't remove the Google Play Services library. We had the discussion about making Cast support optional before, as I had to make it into another library instead of just adding an option, because it's not possible to remove it :/

Why do you need to remove the library?

**Comment by jasongrishkoff** [comment]
If I keep the library in, I get this error when I try to compile: 

```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/auth/api/signin/internal/zzf;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/auth/api/signin/internal/zzf;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    
:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

Seems like a library conflict.  Must be one of my other plugins...

**Comment by jasongrishkoff** [comment]
I think one issue is the library it's conflicting with: https://github.com/devfd/react-native-google-signin

Removing that causes a new error:

```
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/firebase/FirebaseException;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)
    
:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/java-8-oracle/bin/java'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

```

**Comment by Guichaguri** [comment]
Can you try adding both libraries in your build.gradle? That might fix the problem

**Comment by jasongrishkoff** [comment]
That helped!  But I'm back to the C++ error.

I can now compile just fine with no Dex issues because I added this to my build.gradle:

`compile` 'com.google.android.gms:play-services-cast:10.2.1'

So, now I need to figure out that C++ issue.

**Comment by jasongrishkoff** [comment]
Here's a logcat dump:

`04-15 19:03:53.891  3191  3191 E CrashlyticsCore: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: No static method getBatteryLevel(Landroid/content/Context;)F in class Lio/fabric/sdk/android/services/common/CommonUtils; or its super classes (declaration of 'io.fabric.sdk.android.services.common.CommonUtils' appears in /data/app/com.decoderhq.indieshuffle-2/base.apk)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at java.util.concurrent.FutureTask.report(FutureTask.java:94)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at java.util.concurrent.FutureTask.get(FutureTask.java:178)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:235)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore: Caused by: java.lang.NoSuchMethodError: No static method getBatteryLevel(Landroid/content/Context;)F in class Lio/fabric/sdk/android/services/common/CommonUtils; or its super classes (declaration of 'io.fabric.sdk.android.services.common.CommonUtils' appears in /data/app/com.decoderhq.indieshuffle-2/base.apk)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeSessionEvent(CrashlyticsUncaughtExceptionHandler.java:1005)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.writeFatal(CrashlyticsUncaughtExceptionHandler.java:766)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.handleUncaughtException(CrashlyticsUncaughtExceptionHandler.java:262)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.access$100(CrashlyticsUncaughtExceptionHandler.java:55)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:238)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler$5.call(CrashlyticsUncaughtExceptionHandler.java:235)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at io.fabric.sdk.android.services.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:75)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at io.fabric.sdk.android.services.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:30)
04-15 19:03:53.891  3191  3191 E CrashlyticsCore:       at java.lang.Thread.run(Thread.java:818)
04-15 19:03:53.891  3191  3191 E AndroidRuntime: FATAL EXCEPTION: main
04-15 19:03:53.891  3191  3191 E AndroidRuntime: Process: com.decoderhq.indieshuffle, PID: 3191
04-15 19:03:53.891  3191  3191 E AndroidRuntime: com.facebook.react.bridge.UnexpectedNativeTypeException: TypeError: expected dynamic type `int64', but had type `null'
04-15 19:03:53.891  3191  3191 E AndroidRuntime:        at com.facebook.react.bridge.ReadableNativeMap.getInt(Native Method)
04-15 19:03:53.891  3191  3191 E AndroidRuntime:        at com.facebook.react.devsupport.StackTraceHelper.convertJsStackTrace(StackTraceHelper.java:104)
04-15 19:03:53.891  3191  3191 E AndroidRuntime:        at com.facebook.react.devsupport.DevSupportManagerImpl$3.run(DevSupportManagerImpl.java:290)
04-15 19:03:53.891  3191  3191 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
04-15 19:03:53.891  3191  3191 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
04-15 19:03:53.891  3191  3191 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
04-15 19:03:53.891  3191  3191 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
04-15 19:03:53.891  3191  3191 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-15 19:03:53.891  3191  3191 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
04-15 19:03:53.891  3191  3191 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
04-15 19:03:53.892  1629  2952 W ActivityManager:   Force finishing activity com.decoderhq.indieshuffle/.MainActivity
`

**Comment by jasongrishkoff** [comment]
I wonder if I'm missing an SDK related to chromecast.

**Comment by Guichaguri** [comment]
You need to open the SDK Manager and install:
* Google Play Services
* Android Support Repository
* Google Repository

**Comment by jasongrishkoff** [comment]
Have to head out, will try that tomorrow. Thx for the help!

**Comment by jasongrishkoff** [comment]
'tis all up-to-date and the same error persists :(

**Comment by jasongrishkoff** [comment]
Tried rolling back to 0.42.0 from 0.43.3 and same error.

**Comment by jasongrishkoff** [comment]
Okay, so I honed in on the issue which was:
`C++` Exception in 'NativeModules': java.lang.RuntimeException: Got unknown argument class: String[]

I looked all instances of String[] in the library, which basically boil down to "public void remove()".  So, I commented out each of those functions (4 files), and it works!
